### ISSUE TITLE
Button <<clicked: Using shifterBox:MoveEntrie(s)ToRightList() directly in callback EVENT_ENTRY_MOVED won't- re-enable button <<

### ISSUE THREAD

**Issue by Baertram** [klingo/ESO-LibShifterBox#14]
If I register callback to EVENT_ENTRY_MOVED, and inside my callback function I will add items back again to the right box
IF it get's totally empty (e.g. via last item moved per button <, or all items moved per button <<):

The button << will get disabled after all items of the right list are moved to the left list. As the right list should not be empty I re-add 2 "fallback items" to the right list, via the callbackfunction of EVENT_ENTRY_MOVED.
But the button << won't be re-enabled then.
Here is missing some "Is list non-empty" -> then enable the << button again.

Same for the other way around left to right.

**Comment by klingo** [comment]
This is the order of events when the << or >> button is clicked and in the EVENT_ENTRY_MOVED event a new entry added:
![image](https://user-images.githubusercontent.com/14639044/105626925-a173dc80-5e33-11eb-91ff-f16e99652760.png)

So the problem is that the internally the event for adding a new entry is triggered faster, than the event that everything has been removed - thus the << and >> button get disabled even though you added a new entry. Will need to re-design the button-state handler to a generic function that internally counts the elements in the list; then it should always behave correctly.

**Comment by Baertram** [comment]
Thank you!
