### ISSUE TITLE
LeftList entries are always hidden on start, until scrolling (scrollbar is showin entries)

### ISSUE THREAD

**Issue by Baertram** [klingo/ESO-LibShifterBox#23]
https://i.imgur.com/riAMTXT.png
The first view will always hide all leftList entries (even if the list is enabled) until I scroll the list. Then all entries are shown properly.
https://i.imgur.com/SKqzndX.png

Read here for more details: https://gitter.im/klingo

**Comment by Baertram** [comment]
Another very weird behaviour: If I scroll the LibAddonMenu-2.0 panel up the bottom lines of the LibSifterBox will become hidden again. If I scroll down they will be shown again. It looks like there is kind of black box above all entries.
If I scroll inside the left list this black box is hidden again and all items are shown properly, until I scroll the panel again.
Depending on the actual Y position of the LibShifterBox on the UI, inside the LAM panel, the black box moves up/down if I scroll above the LibShifterBox left list.

It's hard to describe and I cannot create a video. Here are some screenshots:

1) Position of LibShifterBox near the top of the LAM panel
https://i.imgur.com/SxAvfGm.png

2) Scrolling up/down above the left list of the LibShifterBox. All items are shown properly
https://i.imgur.com/xJgXJaF.png

3) Scrolling the LAM panel to the top so that the LibShifterBox get's out of the visual area (to the top)
https://i.imgur.com/KYtTve3.png

4) Scrolling the LAM panel down again so the LibShifterbox will get back into he visual area.
https://i.imgur.com/qMpCofR.png

5) Scrolling above the LibShifterBox's left List
https://i.imgur.com/oq2cI4A.png

6) Scrolling the LAM panel down -> The black overlay box appears
https://i.imgur.com/YEZM6Dr.png
At the bottom it is totally overlayin the left list of the LibShifterBox
https://i.imgur.com/IvTxmtx.png

Scrolling above the leftList fixes this again for the moment.

**Comment by klingo** [comment]
Thanks a lot for the report, Baertram!
As discussed via Gitter, the issue does not only happen since 0.4.1, but most likely due to the changes introduced with 0.4.0.
The black box seems to be the Backdrop of the listBox, although it is not clear why it gets detached from the actual list.
Standalone I have not noticed such an issue so far - thus might be related to the integration in LAM?

@Baertram: As discussed, please check if this issue also occurs when integrating on a different level in LAM, respectively when using 'standalone'.

As soon as I get some time, I will check on my side if the issue also occurs with my draft version of a 'native' LAM widget.

**Comment by Baertram** [comment]
This seems to be fixed internally by ZOs now!

**Comment by klingo** [comment]
Cool, thanks for the update! :)
